# Generated by Django 4.2.24 on 2025-09-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_winner_options_remove_draw_eligibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='draw_date',
        ),
        migrations.RemoveField(
            model_name='draw',
            name='eligibility_criteria',
        ),
        migrations.RemoveField(
            model_name='draw',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='draw',
            name='name',
        ),
        migrations.RemoveField(
            model_name='draw',
            name='prize_details',
        ),
        migrations.AddField(
            model_name='draw',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='draw',
            name='draw_type',
            field=models.CharField(choices=[('single', 'Single Winner'), ('multi', 'Multiple Winners')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='draw',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draw',
            name='prize_name',
            field=models.CharField(default='Prize', max_length=200),
        ),
        migrations.AddField(
            model_name='draw',
            name='prize_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='draw',
            name='result_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draw',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draw',
            name='title',
            field=models.CharField(default='Untitled Draw', max_length=255),
        ),
        migrations.AddField(
            model_name='draw',
            name='winners_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
