# Generated by Django 4.2.24 on 2025-11-19 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_draw_draw_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-entry_time']},
        ),
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='draw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='audit_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_record', to='accounts.entry'),
        ),
        migrations.AddField(
            model_name='winner',
            name='method',
            field=models.CharField(default='random_sample', max_length=100),
        ),
        migrations.AddField(
            model_name='winner',
            name='seed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='selected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='winner',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together={('user', 'draw')},
        ),
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together={('draw', 'entry')},
        ),
        migrations.CreateModel(
            name='EntryAdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='accounts.entry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='winner',
            name='won_at',
        ),
    ]
