# Generated by Django 4.2.24 on 2025-11-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_entry_options_alter_winner_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together={('draw', 'position')},
        ),
        migrations.AddField(
            model_name='draw',
            name='winners_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='winner',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_record', to='accounts.entry'),
        ),
    ]
